[package]
name = "vulkan-sandbox"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
ash = "0.38.0"
env_logger = "0.11.8"
glfw = { version = "0.59.0", features = ["vulkan"] }
glm = "0.2.3"
image = "0.25.6"
log = "0.4.27"
num-traits = "0.2.19"
tobj = "4.0.3"
